<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Harvix</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="http://harvix.com/assets/bootstrap.css" rel="stylesheet">
      
	<!-- Fav and touch icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="http://www.harvix.com/images/harvixshort2.jpg">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="http://www.harvix.com/images/harvixshort2.jpg">
      <link rel="apple-touch-icon-precomposed" sizes="72x72" href="http://www.harvix.com/images/harvixshort2.jpg">
                    <link rel="apple-touch-icon-precomposed" href="http://www.harvix.com/images/harvixshort2.jpg">
                                   <link rel="shortcut icon" href="http://www.harvix.com/images/harvixshort2.jpg">
	</head>

  <body>
<?php
$yname = $_REQUEST['yname'] ;
$email = $_REQUEST['email'] ;
$company = $_REQUEST['company'] ;
$website = $_REQUEST['website'] ;
$dtraffic = $_REQUEST['dtraffic'] ;
$drevenue = $_REQUEST['drevenue'] ;
$yrevenue = $_REQUEST['yrevenue'] ;
echo "
$company:
<p></p>
Hello, my name is $yname, writing on behalf of Harvix, an innovative research engine that has recently been designed in California by a group of high school students, and now operates from around the globe. We are writing with an offer of partnership.
<p></p>
There are many advantages to using Harvix, including its facts algorithm, categorized results, note-taking capabilities, and instant information. Our facts feature pulls relevant facts for any given search query from a set of online encyclopedias, including Scholarpedia, Britannica, and Wikipedia. Additionally, our web results are grouped into intelligent categories based on human curation. For example, a search for golden gate bridge will generate results in the categories San-Francisco, History, Travel, Hotels, and Date. There is also a top results category, as well as an images category. Users can also log in to their Harvix accounts and take notes in the cloud with a beautiful documenting application, developed by Harvix. Finally, Harvix offers instant information, which is an expandable first paragraph of the most relevant free online encyclopedia's. Harvix also has a subscription for Wolfram Alpha, which provides some of the best instant information. Oftentimes, users find the information they are looking for just by reading our instant information section. 
<p></p>
Not only does Harvix offer a research engine, but it offers many business solutions as well. We are proposing for elements of Harvix to be strategically included throughout $company's website, as shown in the simulation images attached. We would like to become your website's custom search and web search solution, providing a better custom search experience for users, and better monetization solutions for $company. 
<p></p>
According to websitetheweb.com, $company receives approximately $dtraffic page views per day. When Harvix enters a partnership, we utilize our large array of ad networks and affiliate networks, maximizing revenue and CPM (Ad clicks/affiliate purchases per thousand visitors). Harvix can offer up to 50% of revenue generated by users of $website. Since our CPM is $45, $company and Harvix could each potentially earn about $drevenue per day, or $yrevenue a year. If $company partners with Harvix, they would be able to provide users with a beautiful, revolutionary research engine, while taking advantage of monetization solutions.
<p></p>
Per your request, the Harvix team can create interactive demos to further demonstrate our proposal. We can also provide more background information about our company if you deem it necessary. If you have any questions at all, please email me at $email or our VP Business Development, Jakob Picciotto, at jhpicciotto@gmail.com. Thank you for your time and consideration, and we await your favorable response. 
<p></p>
Best regards,
<p></p>
$yname
<br> 
Harvix Business Development";
?>
</body>
</html>
